# Generated by Django 2.0.2 on 2018-03-29 03:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='用户标识')),
                ('openid', models.CharField(max_length=128, verbose_name='微信OpenId')),
                ('session_key', models.CharField(max_length=128, verbose_name='会话密钥')),
                ('unionid', models.CharField(max_length=128, null=True, verbose_name='统一Id')),
                ('user_info', models.TextField(max_length=512, null=True, verbose_name='用户信息')),
            ],
        ),
        migrations.CreateModel(
            name='Idioms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chengyu', models.CharField(max_length=128, verbose_name='成语')),
                ('pinyin', models.CharField(blank=True, max_length=128, null=True, verbose_name='拼音')),
                ('jianpin', models.CharField(blank=True, max_length=64, null=True, verbose_name='简拼')),
                ('jinyi', models.CharField(blank=True, max_length=512, null=True, verbose_name='近义')),
                ('fanyi', models.CharField(blank=True, max_length=512, null=True, verbose_name='反义')),
                ('yongfa', models.TextField(blank=True, max_length=4096, null=True, verbose_name='用法')),
                ('jieshi', models.TextField(blank=True, max_length=4096, null=True, verbose_name='解释')),
                ('chuchu', models.TextField(blank=True, max_length=4096, null=True, verbose_name='出处')),
                ('lizi', models.TextField(blank=True, max_length=4096, null=True, verbose_name='例子')),
                ('xiehouyu', models.CharField(blank=True, max_length=256, null=True, verbose_name='谒后语')),
                ('miyu', models.CharField(blank=True, max_length=128, null=True, verbose_name='谜语')),
                ('gushi', models.TextField(blank=True, max_length=8192, null=True, verbose_name='成语故事')),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='quizzed',
            field=models.ManyToManyField(to='idiom_quiz1.Idioms', verbose_name='已测试的成语'),
        ),
    ]
