# Generated by Django 2.0.2 on 2018-03-29 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idiom_quiz1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterModelOptions(
            name='idioms',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
