# Generated by Django 2.0.2 on 2018-03-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idiom_quiz1', '0002_auto_20180329_0348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idioms',
            options={'verbose_name': '成语', 'verbose_name_plural': '成语'},
        ),
        migrations.AlterField(
            model_name='appuser',
            name='quizzed',
            field=models.ManyToManyField(editable=False, to='idiom_quiz1.Idioms', verbose_name='已测试的成语'),
        ),
    ]
